import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import power_rangers from "../data/power_rangers.json"
import got_houses from "../data/got_houses.json"
import pokemons from "../data/pokemons.json"

import ServerName from "../components/serverName";

export default function Home() {
  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <ServerName list1={pokemons} list2={got_houses} list3={power_rangers}   />
        </main>
        <footer className={styles.footer}>
          <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          </a>
        </footer>
      </div>
  )
}
